Диплом версия 1
KraynovAlexander/java-explore-with-me pull request #2
Opened 2022-10-11 18:53 UTC by KraynovAlexander

2022-10-12 20:07 UTC, sergeymamonov requested changes

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +public class Checker {
Чаще такой класс называют ...Validator

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +            log.error("Checker: пользователь с id={} не существует", userId);
Здесь не понял, почему в логе и в ошибке сообщения разные. Ниже аналогично.

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +            throw new RequestNotFoundException("не существует запрос не найден");
Не понял сообщения в ошибке.

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/categories/service/CategoryServiceImpl.java
> +            throw new CategoryStillUseException();
Исключение без сообщения, так и задумано?

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/business/service/privates/PrivateRequestServiceImpl.java
> +            throw new ParticipantsException();
Исключение без текста сообщения, так и задумывалось?

2022-10-12 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/main/users/dto/UserDto.java
> +    @Length(max = 60)
Здесь и в модели ограничение в 60 символов для почты и имени, а в базе ограничение в 50 символов.

2022-10-12 20:07 UTC, sergeymamonov commented on stats-server/src/main/java/ru/practicum/main/exception/IncorrectApplicationNameException.java
> +public class IncorrectApplicationNameException extends RuntimeException {
Где-то используется это исключение?

2022-10-15 07:23 UTC, sergeymamonov commented on stats-server/src/main/java/ru/practicum/main/exception/IncorrectApplicationNameException.java
> +public class IncorrectApplicationNameException extends RuntimeException {
Проверьте, я не вижу, где бы использовалось это исключение. Можно проверить либо по глобальному поиску F+Shift+Ctrl, либо через поиск вызовов Ctrl+B

2022-10-15 07:26 UTC, sergeymamonov requested changes
Замечания не устранены

2022-10-15 12:06 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +public class Checker {
Прощу прощения эти замечания не увидел. На сайте практикума посмотрел а сюда не загленул.
Исправлено.

2022-10-15 12:06 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +            throw new RequestNotFoundException("не существует запрос не найден");
Исправлено.

2022-10-15 12:07 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/business/helper/Checker.java
> +            log.error("Checker: пользователь с id={} не существует", userId);
Исправлено.

2022-10-15 12:07 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/categories/service/CategoryServiceImpl.java
> +            throw new CategoryStillUseException();
Исправлено.

2022-10-15 12:08 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/business/service/privates/PrivateRequestServiceImpl.java
> +            throw new ParticipantsException();
Исправил.

2022-10-15 12:08 UTC, KraynovAlexander commented on ewm-service/src/main/java/ru/practicum/main/users/dto/UserDto.java
> +    @Length(max = 60)
Поправил.

2022-10-15 12:09 UTC, KraynovAlexander commented on stats-server/src/main/java/ru/practicum/main/exception/IncorrectApplicationNameException.java
> +public class IncorrectApplicationNameException extends RuntimeException {
Удалил  пока не нужно.

2022-10-15 19:52 UTC, sergeymamonov approved these changes

2022-10-17 19:09 UTC, merged